server:
  port: 7720

spring:
  application:
    name: rundo-auth-gateway
  cloud:
    nacos:
      server-addr: rundo-nacos:8848
      discovery:
        namespace: public
      config:
        file-extension: yml
  config:
    import:
      - optional:nacos:${spring.application.name}

