spring:

  cloud:
    nacos:
      server-addr: rundo-nacos:8848
      username: nacos
      password: rundo@nacos*2023
      discovery:
        namespace: dev
        group: DEFAULT_GROUP
      config:
        namespace: dev
        group: DEFAULT_GROUP

  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml