server:
  port: 8800

spring:
  application:
    name: rundo-auth-gateway
  profiles:
    active: dev

  cloud:
    nacos:
      server-addr: rundo-nacos:8848
      discovery:
        # nacos服务注册中心地址
        # server-addr: rundo-nacos:8848
        # 命名空间
        namespace: dev
        # 分组
        # group:
      config:
        # nacos配置中心地址
        # server-addr: rundo-nacos:8848
        file-extension: yaml
        namespace: dev
        group: DEFAULT_GROUP
        prefix:
