spring:
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER:124.71.21.11:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:rundo@nacos*2023}
      discovery:
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
      config:
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:./static
  # REDIS数据库配置
  redis:
    # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
    host: ${REDIS_HOST:127.0.0.1}
    # [必须修改] 端口号
    port: ${REDIS_PORT:6379}
    # [可选] 数据库 DB
    database: ${REDIS_DB:6}
    # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
    password: rundoredis
    # [可选] 超时时间
    timeout: 10000
    # [可选] jdbc数据库配置, 项目使用sqlite作为数据库，一般不需要配置
    # redisson
#    redisson:
#      file: classpath:redisson.yml
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:127.0.0.1}:${DATABASE_PORT:3306}/${DATABASE_NAME:rundo_cascade_manage}?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PWD:abc123}
    druid:
      query-timeout: 5000
      transaction-query-timeout: 3000
      connect-timeout: 5000
      initial-size: 10                       # 连接池初始化连接数
      max-active: 20                        # 连接池最大连接数
      min-idle: 5                            # 连接池最小空闲连接数
      max-wait: 60000                        # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      keep-alive: true                       # 连接池中的minIdle数量以内的连接，空闲时间超过minEvictableIdleTimeMillis，则会执行keepAlive操作。
      validation-query: select 1             # 检测连接是否有效sql，要求是查询语句，常用select 'x'。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
      test-while-idle: true                   # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-on-borrow: true                   # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false                   # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      pool-prepared-statements: false         # 是否開啟PSCache，並且指定每個連線上PSCache的大小
      time-between-eviction-runs-millis: 60000  # 配置間隔多久才進行一次檢測，檢測需要關閉的空閒連線，單位是毫秒
      min-evictable-idle-time-millis: 600000    # 配置一個連線在池中最小生存的時間，單位是毫秒
      use-global-data-source-stat: true # 合并多个DruidDataSource的监控数据
      filters: config,stat,slf4j            # 配置监控统计拦截的filters，监控统计用的filter:sta, 日志用的filter:log4j, 防御sql注入的filter:wall
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 3000
          db-type: mysql
        wall:
          config:
            multi-statement-allow: true
            none-base-statement-allow: true
      stat-view-servlet:
        # 访问白名单
        allow: 127.0.0.1
        enabled: true
        url-pattern: /druid/*
        login-username: druid
        login-password: rundodruid
        # 允许重置监控数据
        reset-enable: true
      web-stat-filter:
        # 配置统计页面过滤
        enabled: true
        # 排除路径
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
        # 开启session统计
        session-stat-enable: true
        # session统计的最大个数
        session-stat-max-count: 100
        # 过滤路径
        url-pattern: /*
  mvc:
    async:
      request-timeout: 15000
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
server:
  port: ${SERVER_PORT:8095}
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/css
  undertow:
    threads:
      worker: 200
      io: 100
    no-request-timeout: 60000
    buffer-size: 32768
    direct-buffers: true

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# [可选] 日志配置, 一般不需要改
logging:
  config: classpath:logback-spring.xml

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 30000
        read-timeout: 30000
        logger-level: basic

cascade:
  local:
    name: 润健视频平台
    ip: 127.0.0.1
    port: 8095
    gb-domain: 11233344
    gb-code: 11233344
# 作为28181服务器的配置
sip:
  # [必须修改] 本机的IP
  ip:  172.20.0.78
  # [可选] 28181服务监听的端口
  port: 5011
  # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
  # 后两位为行业编码，定义参照附录D.3
  # 3701020049标识山东济南历下区 信息行业接入
  # [可选]
  domain: 4401020049
  # [可选]
  id: 44010200492000000001
  # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
  password: rundo@2023
  # [可选] 心跳超时时间， 建议设置为心跳周期的三倍
  keepalive-timeout: 255
  # [可选] 国标级联注册失败，再次发起注册的时间间隔。 默认60秒
  register-time-interval: 60
  # [可选] 云台控制速度
  ptz-speed: 100
  # 字符编码
  characterSet: GB23132
  # 注册过期时间 s
  expires: 300