spring:
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER:rundo-nacos:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:rundo@nacos*2023}
      discovery:
        namespace: ${NACOS_NAMESPACE:uat}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
      config:
        namespace: ${NACOS_NAMESPACE:uat}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml
server:
  port: ${SERVER_PORT:8080}