version: '3'
services:
  device-control:
    image: xard-harbor.runjian.com:20443/hyy-rundo-gms/rundo-device-control:${version}
    container_name: device-control
    restart: on-failure
    ports:
      - 8090:8090
    volumes:
      - ./logs/:/opt/device-control/logs/
      - ./config/application.yml:/opt/device-control/config/application.yml
    environment:
      TZ: Asia/Shanghai
      SERVER_PORT: 8090
      PROFILES_ACTIVE: "prod"
      NACOS_SERVER: 124.71.21.11:8848
      NACOS_NAMESPACE: test
      NACOS_USERNAME: nacos
      NACOS_GROUP: DEFAULT_GROUP
      NACOS_PASSWORD: rundo@nacos*2023
    logging:
      options:
        max-size: '12m'
        max-file: '10'
    networks:
      - proxynet
networks:
  proxynet:
    external:
      name: rundo_network
