version: '3'
services:
  parsing-engine:
    image: xard-harbor.runjian.com:20443/hyy-rundo-gms/rundo-parsing-engine:${version}
    container_name: parsing-engine
    restart: on-failure
    ports:
      - 8091:8091
    volumes:
      - ./logs/:/opt/parsing-engine/logs/
    environment:
      TZ: Asia/Shanghai
      SERVER_PORT: 8091
      PROFILES_ACTIVE: test
      NACOS_SERVER: 192.168.0.84:8848
      NACOS_NAMESPACE: test
      NACOS_USERNAME: nacos
      NACOS_GROUP: DEFAULT_GROUP
      NACOS_PASSWORD: rundo@nacos*2023
    logging:
      options:
        max-size: '12m'
        max-file: '10'
    networks:
      - proxynet
networks:
  proxynet:
    external:
      name: rundo_network
