spring:
    application:
        name: gb28181-server
    web:
        resources:
            static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:./static
    # REDIS数据库配置
    redis:
        # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
        host: 127.0.0.1
        # [必须修改] 端口号
        port: 6379
        # [可选] 数据库 DB
        database: 6
        # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
        password: rundoredis
        # [可选] 超时时间

server:
    port: 8061

# 作为28181服务器的配置
sip:
    # [必须修改] 本机的IP
    ip:  172.20.0.78
    # [可选] 28181服务监听的端口
    port: 5011
    # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
    # 后两位为行业编码，定义参照附录D.3
    # 3701020049标识山东济南历下区 信息行业接入
    # [可选]
    domain: 4401020049
    # [可选]
    id: 44010200492000000001
    # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
    password: rundo@2023
    # [可选] 心跳超时时间， 建议设置为心跳周期的三倍
    keepalive-timeout: 255
    # [可选] 国标级联注册失败，再次发起注册的时间间隔。 默认60秒
    register-time-interval: 60
    # [可选] 云台控制速度
    ptz-speed: 100
    # 字符编码
    characterSet: GB23132
    # 注册过期时间 s
    expires: 300


# [可选] 日志配置, 一般不需要改
logging:
    config: classpath:logback-spring-local.xml

