
### 登录接口
POST {{host}}:{{port}}/auth/user/login
Content-Type: application/json;charset=UTF-8

{
  "username": "admin",
  "password": "123456"
}

> {%
    // 设置选中环境的全局变量
    client.global.set("tokenx", response.body.data.token);
    // 添加断言
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### 注销接口
POST {{host}}:{{port}}/auth/user/logout
Content-Type: application/json;charset=UTF-8
Authorization: {{tokenx}}

### 添加用户
POST {{host}}:{{port}}/auth/sysUserInfo/add
Content-Type: application/json;charset=UTF-8
Authorization: {{tokenx}}

{
  "userAccount": "restfulToolkitX",
  "userName": "restfulToolkitX",
  "password": "restfulToolkitX",
  "rePassword": "restfulToolkitX",
  "expiryDateStart": "2022-01-31 00:00:00",
  "orgId": 1,
  "jobNo": "restfulToolkitX",
  "address": "restfulToolkitX",
  "email": "restfulToolkitX",
  "phone": "restfulToolkitX",
  "description": "restfulToolkitX",
  "roleIds": [
    1
  ]
}

### 通过ID获取用户信息
POST {{host}}:{{port}}/auth/sysUserInfo/getById/1
Content-Type: application/json;charset=UTF-8
Authorization: {{tokenx}}

### 更新用户信息
POST {{host}}:{{port}}/auth/sysUserInfo/update
Content-Type: application/json;charset=UTF-8
Authorization: {{tokenx}}

{
  "id": "1646811695394041857",
  "userAccount": "restfulToolkitX",
  "userName": "restfulToolkitX",
  "password": "restfulToolkitX",
  "rePassword": "restfulToolkitX",
  "expiryDateStart": "2022-02-01 00:00:00",
  "orgId": 1,
  "jobNo": "restfulToolkitX",
  "address": "restfulToolkitX",
  "email": "restfulToolkitX",
  "phone": "restfulToolkitX",
  "description": "restfulToolkitX",
  "roleIds": [
    1
  ]
}

### 转换用户禁用状态
POST {{host}}:{{port}}/auth/sysUserInfo/status/change
Content-Type: application/json;charset=UTF-8
Authorization: {{tokenx}}

{
  "id": "1646811695394041857",
  "status": 1
}

### 删除用户
POST {{host}}:{{port}}/auth/sysUserInfo/remove/1646811695394041857
Content-Type: application/json;charset=UTF-8
Authorization: {{tokenx}}

### 批量删除用户
POST {{host}}:{{port}}/auth/sysUserInfo/batchRemove
Content-Type: application/json;charset=UTF-8
Authorization: {{tokenx}}

[1646811695394041857]

### 分页查询用户
POST {{host}}:{{port}}/auth/sysUserInfo/getListByPage
Content-Type: application/json;charset=UTF-8
Authorization: {{tokenx}}

{
  "orgId": 1,
  "contain": 1,
  "userAccount": "restfulToolkitX",
  "userName": "restfulToolkitX"
}

### 关联用户查看单个用户信息
POST {{host}}:{{port}}/auth/sysUserInfo/getRelationSysUserInfo/1
Content-Type: application/json;charset=UTF-8
Authorization: {{tokenx}}

### 关联用户用户列表查询
POST {{host}}:{{port}}/auth/sysUserInfo/getRelationSysUserInfoList
Content-Type: application/json;charset=UTF-8
Authorization: {{tokenx}}

{

}

###
POST {{host}}:{{port}}/auth/sysMenuInfo/tree
Content-Type: application/json;charset=UTF-8
Authorization: {{tokenx}}

{}


