spring:
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER:124.71.21.11:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:rundo@nacos*2023}
      discovery:
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
      config:
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:./static
  # REDIS数据库配置
  redis:
    # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
    host: ${REDIS_HOST:127.0.0.1}
    # [必须修改] 端口号
    port: ${REDIS_PORT:6379}
    # [可选] 数据库 DB
    database: ${REDIS_DB:6}
    # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
    password:
    # [可选] 超时时间
    timeout: 10000
    # [可选] jdbc数据库配置, 项目使用sqlite作为数据库，一般不需要配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:127.0.0.1}:${DATABASE_PORT:3306}/${DATABASE_NAME:rundo_parsing_engine}?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PWD:abc123}
    druid:
      query-timeout: 5000
      transaction-query-timeout: 3000
      connect-timeout: 5000
      initial-size: 10                       # 连接池初始化连接数
      max-active: 20                        # 连接池最大连接数
      min-idle: 5                            # 连接池最小空闲连接数
      max-wait: 60000                        # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      keep-alive: true                       # 连接池中的minIdle数量以内的连接，空闲时间超过minEvictableIdleTimeMillis，则会执行keepAlive操作。
      validation-query: select 1             # 检测连接是否有效sql，要求是查询语句，常用select 'x'。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
      test-while-idle: true                   # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-on-borrow: true                   # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false                   # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      pool-prepared-statements: false         # 是否開啟PSCache，並且指定每個連線上PSCache的大小
      time-between-eviction-runs-millis: 60000  # 配置間隔多久才進行一次檢測，檢測需要關閉的空閒連線，單位是毫秒
      min-evictable-idle-time-millis: 600000    # 配置一個連線在池中最小生存的時間，單位是毫秒
      use-global-data-source-stat: true # 合并多个DruidDataSource的监控数据
      filters: config,stat,slf4j            # 配置监控统计拦截的filters，监控统计用的filter:sta, 日志用的filter:log4j, 防御sql注入的filter:wall
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 3000
          db-type: mysql
        wall:
          config:
            multi-statement-allow: true
            none-base-statement-allow: true
      stat-view-servlet:
        # 访问白名单
        allow: 127.0.0.1
        enabled: true
        url-pattern: /druid/*
        login-username: druid
        login-password: rundodruid
        # 允许重置监控数据
        reset-enable: true
      web-stat-filter:
        # 配置统计页面过滤
        enabled: true
        # 排除路径
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
        # 开启session统计
        session-stat-enable: true
        # session统计的最大个数
        session-stat-max-count: 100
        # 过滤路径
        url-pattern: /*
  rabbitmq:
    host:  ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:wvp}
    password: ${RABBITMQ_PASSWORD:wvp12345678}
    publisher-returns: true      # 消息发送到交换机确认机制，是否确认回调
    #        publisher-confirm-type: correlated
    template:
      mandatory: true           #不可达消息是否回调,false时会忽略掉spring.rabbitmq.publisher-returns属性的值
    listener:
      simple:
        concurrency: 8            # 指定最小的消费者数量
        max-concurrency: 32       # 指定最大的消费者数量
        acknowledge-mode: manual  # 采用手动应答
        retry:
          enabled: true           # 是否支持重试
  mvc:
    async:
      request-timeout: 15000

server:
  port: ${SERVER_PORT:8091}
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/css
  undertow:
    threads:
      worker: 200
      io: 100
    no-request-timeout: 60000
    buffer-size: 32768
    direct-buffers: true

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# [可选] 日志配置, 一般不需要改
logging:
  config: classpath:logback-spring.xml

mq:
  enabled: true
  queue-data-list:
    - id: PUBLIC-GS
      routing-key: rundo.public.gs
      queue-name: rundo.public.gs
      exchange-id: PUBLIC
      ttl: 15000
    - id: PUBLIC-SG
      routing-key: rundo.public.sg
      queue-name: rundo.public.sg
      exchange-id: PUBLIC
      ttl: 15000
  exchange-data-list:
    - id: PUBLIC
      name: rundo.public
      type: topic
    - id: GATEWAY
      name: rundo.gateway
      type: topic
    - id: STREAM
      name: rundo.stream
      type: topic

mq-default:
  public:
    queue-id-get: PUBLIC-SG
    queue-id-set: PUBLIC-GS
  exchange:
    public: PUBLIC
    gateway: GATEWAY
    stream: STREAM

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 15000
        read-timeout: 15000
        logger-level: basic

resilience4j:
  ratelimiter: #限流
    configs:
      default:
        timeoutDuration: 5 # 线程等待权限的默认等待时间
        limitRefreshPeriod: 1s # 限流器每隔1s刷新⼀次，将允许处理的最⼤请求重置为100
        limitForPeriod: 100 #在⼀个刷新周期内，允许执⾏的最⼤请求数
  timelimiter: #超时处理
    configs:
      default:
        timeout-duration: 15s # 请求超时时间
        cancel-running-future: true # 取消运行
  circuitbreaker: # 断路器
    configs:
      default:
        failureRateThreshold: 80 #失败请求百分⽐，超过这个⽐例，CircuitBreaker变为OPEN状态
        slidingWindowSize: 3 #滑动窗⼝的⼤⼩，配置COUNT_BASED,表示10个请求，配置TIME_BASED表示10秒
        minimumNumberOfCalls: 10 #最⼩请求个数，只有在滑动窗⼝内，请求个数达到这个个数，才会触发CircuitBreader对于断路器的判断
        slidingWindowType: TIME_BASED #滑动窗⼝的类型
        permittedNumberOfCallsInHalfOpenState: 3 #当CircuitBreaker处于HALF_OPEN状态的时候，允许通过的请求个数
        automaticTransitionFromOpenToHalfOpenEnabled: true #设置true，表示⾃动从OPEN变成HALF_OPEN，即使没有请求过来
        waitDurationInOpenState: 1s #从OPEN到HALF_OPEN状态需要等待的时间
        recordExceptions: #异常名单
          - java.lang.Exception