version: '3'
services:
  stream-manage:
    image: xard-harbor.runjian.com:20443/hyy-rundo-gms/rundo-stream-manage:${version}
    container_name: stream-manage
    restart: on-failure
    ports:
      - 8092:8092
    volumes:
      - ./logs/:/opt/stream-manage/logs/
    environment:
      TZ: Asia/Shanghai
      SERVER_PORT: 8092
      PROFILES_ACTIVE: dev
      NACOS_SERVER: 192.168.0.84:8848
      NACOS_NAMESPACE: test
      NACOS_USERNAME: nacos
      NACOS_GROUP: DEFAULT_GROUP
      NACOS_PASSWORD: rundo@nacos*2023
    logging:
      options:
        max-size: '12m'
        max-file: '10'
    networks:
      - proxynet
networks:
  proxynet:
    external:
      name: rundo_network
