spring:
  application:
    name: device-expansion
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: rundo-nacos:8848
        namespace: public
    inetutils:
      ignored-interfaces:

  # REDIS数据库配置
  redis:
    # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
    host: rundo-redis
    # [必须修改] 端口号
    port: 6379
    # [可选] 数据库 DB
    database: 6
    # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
    password: rundoredis
    # [可选] 超时时间
    timeout: 10000
    # redisson
    redisson:
      file: classpath:redisson.yml
    # [可选] jdbc数据库配置, 项目使用sqlite作为数据库，一般不需要配置
    # mysql数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rundo_expansion_server?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: root123
    druid:
      initialSize: 10                       # 连接池初始化连接数
      maxActive: 200                        # 连接池最大连接数
      minIdle: 5                            # 连接池最小空闲连接数
      maxWait: 60000                        # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      keepAlive: true                       # 连接池中的minIdle数量以内的连接，空闲时间超过minEvictableIdleTimeMillis，则会执行keepAlive操作。
      validationQuery: select 1             # 检测连接是否有效sql，要求是查询语句，常用select 'x'。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
      testWhileIdle: true                   # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testOnBorrow: false                   # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      testOnReturn: false                   # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      poolPreparedStatements: false         # 是否開啟PSCache，並且指定每個連線上PSCache的大小
      timeBetweenEvictionRunsMillis: 60000  # 配置間隔多久才進行一次檢測，檢測需要關閉的空閒連線，單位是毫秒
      minEvictableIdleTimeMillis: 300000    # 配置一個連線在池中最小生存的時間，單位是毫秒
      filters: config,stat,slf4j             # 配置监控统计拦截的filters，监控统计用的filter:sta, 日志用的filter:log4j, 防御sql注入的filter:wall
      filter:
        wall:
          config:
            multi-statement-allow: true
      useGlobalDataSourceStat: true         # 合并多个DruidDataSource的监控数据
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
      #stat-view-servlet.url-pattern: /admin/druid/*

  # rabbitmq 配置
  rabbitmq:
    host: rundo-mq
    port: 5672
    username: wvp
    password: wvp12345678
    publisher-returns: true      # 消息发送到交换机确认机制，是否确认回调
    #        publisher-confirm-type: correlated
    template:
      mandatory: true           #不可达消息是否回调,false时会忽略掉spring.rabbitmq.publisher-returns属性的值
    listener:
      simple:
        concurrency: 8            # 指定最小的消费者数量
        max-concurrency: 32       # 指定最大的消费者数量
        acknowledge-mode: manual  # 采用手动应答
        retry:
          enabled: true           # 是否支持重试

server:
  port: 8060

feign:
  circuitbreaker:
    enabled: true # 上面无效 使用下面 服务降级
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: basic




# [可选] 日志配置, 一般不需要改
logging:
  config: classpath:logback-spring.xml

mybatis-plus:
  global-config:
    banner: off
    db-config:
      # logic-delete-field是entity的属性名
      logic-delete-field: deleteFlag
      # 1 代表已删除，不配置默认是1
      logic-delete-value: 1
      # 0 代表未删除，不配置默认是0
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

response:
  exclude-url: "/swagger-resources,/doc.html,/v3/api-docs,/api/v1"

springfox:
  documentation:
    auto-startup: true
knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-document-manage: true
    enable-reload-cache-parameter: true
    enable-request-cache: true
    enable-filter-multipart-apis: true
    enable-debug: true
    enable-open-api: true
    enable-group: true
  openapi:
    title: 润建视频平台接口文档
    description: 资源扩展服务接口
    email: 97180@runjian.com
    concat: cjl
    url: https://docs.runjian.com
    version: v1.0.0