server:
  port: 8801
  servlet:
    context-path: /oauth2/

spring:
  application:
    name: rundo-auth-server
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev

  cloud:
    nacos:
      discovery:
        # nacos服务注册中心地址
        server-addr: rundo-nacos:8848
        # 命名空间
        # namespace: public
        # 分组
        # group:

      config:
        # nacos配置中心地址
        server-addr: rundo-nacos:8848
        file-extension: yaml
        namespace: dev
        # group:
        prefix:
  redis:
    host: rundo-redis
    port: 6379
    database: 0
    password: 123456
    timeout: 1800
    lettuce:
      pool:
        max-active: 20
        max-wait: 60
        max-idle: 5
        min-idle: 0
      shutdown-timeout: 100

