base:
  config:
    db:
      hostname: rundo-mysql
      port: 3306
      database: rundo_rbac
      username: root
      password: JiangYu)1234
    redis:
      hostname: rundo-redis
      port: 6379
      database: 0
      password: root_6379

server:
  port: 8801
#  servlet:
#    context-path: /oauth2

spring:
  application:
    name: rundo-auth-server
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${base.config.db.hostname}:${base.config.db.port}/${base.config.db.database}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ${base.config.db.username}
    password: ${base.config.db.password}
    hikari:
      pool-name: MyHikariCP
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  cloud:
    nacos:
      discovery:
        # nacos服务注册中心地址
        server-addr: rundo-nacos:8848
        # 命名空间
        namespace: public
        # 分组
        # group:

      config:
        # nacos配置中心地址
        server-addr: rundo-nacos:8848
        file-extension: yaml
        namespace: dev
        # group:
        prefix:
  redis:
    host: ${base.config.redis.hostname}
    port: ${base.config.redis.port}
    database: ${base.config.redis.database}
    password: ${base.config.redis.password}
    timeout: 1800
    lettuce:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0

mybatis-plus:
  global-config:
    banner: off
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    org.springframework.security: debug
    # 过滤器执行顺序
    org.springframework.security.web.FilterChainProxy: trace
    # 异常处理
    org.springframework.security.web.access.ExceptionTranslationFilter: trace
