server:
  port: 8801
  servlet:
    context-path: /oauth2/

spring:
  application:
    name: rundo-auth-server
  profiles:
    active: dev

  cloud:
    nacos:
      discovery:
        # nacos服务注册中心地址
        server-addr: rundo-nacos:8848
        # 命名空间
        # namespace: public
        # 分组
        # group:

      config:
        # nacos配置中心地址
        server-addr: rundo-nacos:8848
        file-extension: yaml
        namespace: dev
        # group:
        prefix:
