server:
  port: 7821
  servlet:
    context-path: /rundoAuthServer

spring:
  application:
    name: rundo-auth-server
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rundo-mysql:3306/rundo_rbac?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: rundomysql
    druid:
      # 连接池初始化时创建的连接数量
      initial-size: 5
      # 连接的最⼩空闲数量
      min-idle: 5
      # 最⼤活跃的连接数量
      max-active: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 60000
      time-between-eviction-runs-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      use-global-data-source-stat: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 111111
        web-stat-filter:
          enabled: true
          url-pattern: /*
          exclusions: /druid/*, *.js, *.jpeg, *.jpg, *.png, *.gif, *.css
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 3000
          log-slow-sql: true
  cloud:
    nacos:
      # nacos服务注册中心地址
      server-addr: rundo-nacos:8848
      discovery:
        # 命名空间
        namespace: public
        # 分组
        # group:
      config:
        file-extension: yaml
        namespace: public
        group: DEFAULT_GROUP
        prefix:
  config:
    import:
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
  redis:
    host: rundo-redis
    port: 6379
    database: 0
    password: rundoredis
    timeout: 1800
    lettuce:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0

mybatis-plus:
  global-config:
    banner: off
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    org.springframework.security: debug
    # 过滤器执行顺序
    org.springframework.security.web.FilterChainProxy: trace
    # 异常处理
    org.springframework.security.web.access.ExceptionTranslationFilter: trace

springfox:
  documentation:
    auto-startup: true
knife4j:
  enable: true
  setting:
    language: zh-CN
    swagger-model-name:
  openapi:
    title: 视频平台接口文档
    description: 润建视频平台接口文档
    email: 105194@runjian.com
    concat: jiangyu
    url: https://docs.runjian.com
    version: v1.0.0